package com.aula.literatiapp.presentation.ui.theme
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006D3D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF63E799)
val onPrimaryContainerLight = Color(0xFF004625)
val secondaryLight = Color(0xFF296C00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF92F061)
val onSecondaryContainerLight = Color(0xFF1B4C00)
val tertiaryLight = Color(0xFF2A6675)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF7CB5C5)
val onTertiaryContainerLight = Color(0xFF00252E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF4FBF2)
val onBackgroundLight = Color(0xFF161D18)
val surfaceLight = Color(0xFFF4FBF2)
val onSurfaceLight = Color(0xFF161D18)
val surfaceVariantLight = Color(0xFFD8E6D8)
val onSurfaceVariantLight = Color(0xFF3D4A40)
val outlineLight = Color(0xFF6D7A6F)
val outlineVariantLight = Color(0xFFBCCABD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B322C)
val inverseOnSurfaceLight = Color(0xFFEBF3EA)
val inversePrimaryLight = Color(0xFF5ADE91)
val surfaceDimLight = Color(0xFFD5DCD3)
val surfaceBrightLight = Color(0xFFF4FBF2)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEEF6EC)
val surfaceContainerLight = Color(0xFFE9F0E7)
val surfaceContainerHighLight = Color(0xFFE3EAE1)
val surfaceContainerHighestLight = Color(0xFFDDE5DB)

val primaryLightMediumContrast = Color(0xFF004E2A)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF00864C)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF1B4D00)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF348500)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF004A58)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF437C8C)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF4FBF2)
val onBackgroundLightMediumContrast = Color(0xFF161D18)
val surfaceLightMediumContrast = Color(0xFFF4FBF2)
val onSurfaceLightMediumContrast = Color(0xFF161D18)
val surfaceVariantLightMediumContrast = Color(0xFFD8E6D8)
val onSurfaceVariantLightMediumContrast = Color(0xFF39463C)
val outlineLightMediumContrast = Color(0xFF556257)
val outlineVariantLightMediumContrast = Color(0xFF717E72)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B322C)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEBF3EA)
val inversePrimaryLightMediumContrast = Color(0xFF5ADE91)
val surfaceDimLightMediumContrast = Color(0xFFD5DCD3)
val surfaceBrightLightMediumContrast = Color(0xFFF4FBF2)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEEF6EC)
val surfaceContainerLightMediumContrast = Color(0xFFE9F0E7)
val surfaceContainerHighLightMediumContrast = Color(0xFFE3EAE1)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDDE5DB)

val primaryLightHighContrast = Color(0xFF002913)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004E2A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0B2800)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF1B4D00)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00262F)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF004A58)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF4FBF2)
val onBackgroundLightHighContrast = Color(0xFF161D18)
val surfaceLightHighContrast = Color(0xFFF4FBF2)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFD8E6D8)
val onSurfaceVariantLightHighContrast = Color(0xFF1B271E)
val outlineLightHighContrast = Color(0xFF39463C)
val outlineVariantLightHighContrast = Color(0xFF39463C)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B322C)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFA8FFC3)
val surfaceDimLightHighContrast = Color(0xFFD5DCD3)
val surfaceBrightLightHighContrast = Color(0xFFF4FBF2)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEEF6EC)
val surfaceContainerLightHighContrast = Color(0xFFE9F0E7)
val surfaceContainerHighLightHighContrast = Color(0xFFE3EAE1)
val surfaceContainerHighestLightHighContrast = Color(0xFFDDE5DB)

val primaryDark = Color(0xFFA4FFC1)
val onPrimaryDark = Color(0xFF00391D)
val primaryContainerDark = Color(0xFF54D98D)
val onPrimaryContainerDark = Color(0xFF003B1F)
val secondaryDark = Color(0xFFE8FFD5)
val onSecondaryDark = Color(0xFF123800)
val secondaryContainerDark = Color(0xFF86E456)
val onSecondaryContainerDark = Color(0xFF174400)
val tertiaryDark = Color(0xFF96CFE0)
val onTertiaryDark = Color(0xFF003640)
val tertiaryContainerDark = Color(0xFF68A1B1)
val onTertiaryContainerDark = Color(0xFF00070A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1510)
val onBackgroundDark = Color(0xFFDDE5DB)
val surfaceDark = Color(0xFF0E1510)
val onSurfaceDark = Color(0xFFDDE5DB)
val surfaceVariantDark = Color(0xFF3D4A40)
val onSurfaceVariantDark = Color(0xFFBCCABD)
val outlineDark = Color(0xFF869488)
val outlineVariantDark = Color(0xFF3D4A40)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE5DB)
val inverseOnSurfaceDark = Color(0xFF2B322C)
val inversePrimaryDark = Color(0xFF006D3D)
val surfaceDimDark = Color(0xFF0E1510)
val surfaceBrightDark = Color(0xFF343B35)
val surfaceContainerLowestDark = Color(0xFF09100B)
val surfaceContainerLowDark = Color(0xFF161D18)
val surfaceContainerDark = Color(0xFF1A211C)
val surfaceContainerHighDark = Color(0xFF252C26)
val surfaceContainerHighestDark = Color(0xFF2F3630)

val primaryDarkMediumContrast = Color(0xFFA4FFC1)
val onPrimaryDarkMediumContrast = Color(0xFF00391D)
val primaryContainerDarkMediumContrast = Color(0xFF54D98D)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000C04)
val secondaryDarkMediumContrast = Color(0xFFE8FFD5)
val onSecondaryDarkMediumContrast = Color(0xFF123800)
val secondaryContainerDarkMediumContrast = Color(0xFF86E456)
val onSecondaryContainerDarkMediumContrast = Color(0xFF061E00)
val tertiaryDarkMediumContrast = Color(0xFF9AD4E4)
val onTertiaryDarkMediumContrast = Color(0xFF001920)
val tertiaryContainerDarkMediumContrast = Color(0xFF68A1B1)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1510)
val onBackgroundDarkMediumContrast = Color(0xFFDDE5DB)
val surfaceDarkMediumContrast = Color(0xFF0E1510)
val onSurfaceDarkMediumContrast = Color(0xFFF6FDF3)
val surfaceVariantDarkMediumContrast = Color(0xFF3D4A40)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC0CEC1)
val outlineDarkMediumContrast = Color(0xFF99A69A)
val outlineVariantDarkMediumContrast = Color(0xFF79877B)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDDE5DB)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252C26)
val inversePrimaryDarkMediumContrast = Color(0xFF00532D)
val surfaceDimDarkMediumContrast = Color(0xFF0E1510)
val surfaceBrightDarkMediumContrast = Color(0xFF343B35)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF09100B)
val surfaceContainerLowDarkMediumContrast = Color(0xFF161D18)
val surfaceContainerDarkMediumContrast = Color(0xFF1A211C)
val surfaceContainerHighDarkMediumContrast = Color(0xFF252C26)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF2F3630)

val primaryDarkHighContrast = Color(0xFFEFFFEF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF5FE395)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFF2FFE5)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF86E456)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF4FCFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9AD4E4)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0E1510)
val onBackgroundDarkHighContrast = Color(0xFFDDE5DB)
val surfaceDarkHighContrast = Color(0xFF0E1510)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3D4A40)
val onSurfaceVariantDarkHighContrast = Color(0xFFF0FFF0)
val outlineDarkHighContrast = Color(0xFFC0CEC1)
val outlineVariantDarkHighContrast = Color(0xFFC0CEC1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDDE5DB)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF003119)
val surfaceDimDarkHighContrast = Color(0xFF0E1510)
val surfaceBrightDarkHighContrast = Color(0xFF343B35)
val surfaceContainerLowestDarkHighContrast = Color(0xFF09100B)
val surfaceContainerLowDarkHighContrast = Color(0xFF161D18)
val surfaceContainerDarkHighContrast = Color(0xFF1A211C)
val surfaceContainerHighDarkHighContrast = Color(0xFF252C26)
val surfaceContainerHighestDarkHighContrast = Color(0xFF2F3630)
val DarkGrey= Color(0XFF1F1F1F)
val Purple = Color(0XFF830EF7)

// text colors

// gradient brush
val gradientBrushLight = Brush.horizontalGradient(
    listOf(
        primaryContainerLight,
        secondaryContainerLight
    )
)

val gradientBrushLightMediumContrast = Brush.horizontalGradient(
    listOf(
        primaryContainerLightMediumContrast,
        secondaryContainerLightMediumContrast
    )
)

val gradientBrushDark = Brush.horizontalGradient(
    listOf(
        primaryContainerDark,
        secondaryContainerDark
    )

)

val gradientBrushLightHighContrast = Brush.horizontalGradient(
    listOf(
        primaryContainerLightHighContrast,
        secondaryContainerLightHighContrast
    )
)

val gradientBrushDarkMediumContrast = Brush.horizontalGradient(
    listOf(
        primaryContainerDarkMediumContrast,
        secondaryContainerDarkMediumContrast
    )

)

val gradientBrushDarkHighContrast = Brush.horizontalGradient(
    listOf(
        primaryContainerDarkHighContrast,
        secondaryContainerDarkHighContrast
    )
)





